import {FacilityCodeMap} from "./KnownCodes.ts";

const setupApiErr: FacilityCodeMap = {
    0x0: 'SPAPI_E_EXPECTED_SECTION_NAME - A non-empty line was encountered in the INF before the start of a section.',
    0x1: 'SPAPI_E_BAD_SECTION_NAME_LINE - A section name marker in the INF is not complete, or does not exist on a line by itself.',
    0x2: 'SPAPI_E_SECTION_NAME_TOO_LONG - An INF section was encountered whose name exceeds the maximum section name length.',
    0x3: 'SPAPI_E_GENERAL_SYNTAX - The syntax of the INF is invalid.',

    0x100: 'SPAPI_E_WRONG_INF_STYLE - The style of the INF is different than what was requested.',
    0x101: 'SPAPI_E_SECTION_NOT_FOUND - The required section was not found in the INF.',
    0x102: 'SPAPI_E_LINE_NOT_FOUND - The required line was not found in the INF.',
    0x103: 'SPAPI_E_NO_BACKUP - The files affected by the installation of this file queue have not been backed up for uninstall.',

    0x200: 'SPAPI_E_NO_ASSOCIATED_CLASS - The INF or the device information set or element does not have an associated install class.',
    0x201: 'SPAPI_E_CLASS_MISMATCH - The INF or the device information set or element does not match the specified install class.',
    0x202: 'SPAPI_E_DUPLICATE_FOUND - An existing device was found that is a duplicate of the device being manually installed.',
    0x203: 'SPAPI_E_NO_DRIVER_SELECTED - There is no driver selected for the device information set or element.',
    0x204: 'SPAPI_E_KEY_DOES_NOT_EXIST - The requested device registry key does not exist.',
    0x205: 'SPAPI_E_INVALID_DEVINST_NAME - The device instance name is invalid.',
    0x206: 'SPAPI_E_INVALID_CLASS - The install class is not present or is invalid.',
    0x207: 'SPAPI_E_DEVINST_ALREADY_EXISTS - The device instance cannot be created because it already exists.',
    0x208: 'SPAPI_E_DEVINFO_NOT_REGISTERED - The operation cannot be performed on a device information element that has not been registered.',
    0x209: 'SPAPI_E_INVALID_REG_PROPERTY - The device property code is invalid.',
    0x20A: 'SPAPI_E_NO_INF - The INF from which a driver list is to be built does not exist.',
    0x20B: 'SPAPI_E_NO_SUCH_DEVINST - The device instance does not exist in the hardware tree.',
    0x20C: 'SPAPI_E_CANT_LOAD_CLASS_ICON - The icon representing this install class cannot be loaded.',
    0x20D: 'SPAPI_E_INVALID_CLASS_INSTALLER - The class installer registry entry is invalid.',
    0x20E: 'SPAPI_E_DI_DO_DEFAULT - The class installer has indicated that the default action should be performed for this installation request.',
    0x20F: 'SPAPI_E_DI_NOFILECOPY - The operation does not require any files to be copied.',
    0x210: 'SPAPI_E_INVALID_HWPROFILE - The specified hardware profile does not exist.',
    0x211: 'SPAPI_E_NO_DEVICE_SELECTED - There is no device information element currently selected for this device information set.',
    0x212: 'SPAPI_E_DEVINFO_LIST_LOCKED - The operation cannot be performed because the device information set is locked.',
    0x213: 'SPAPI_E_DEVINFO_DATA_LOCKED - The operation cannot be performed because the device information element is locked.',
    0x214: 'SPAPI_E_DI_BAD_PATH - The specified path does not contain any applicable device INFs.',
    0x215: 'SPAPI_E_NO_CLASSINSTALL_PARAMS - No class installer parameters have been set for the device information set.',
    0x216: 'SPAPI_E_FILEQUEUE_LOCKED - The operation cannot be performed because the file queue is locked.',
    0x217: 'SPAPI_E_BAD_SERVICE_INSTALLSECT - A service installation section in this INF is invalid.',
    0x218: 'SPAPI_E_NO_CLASS_DRIVER_LIST - There is no class driver list for the device information element.',
    0x219: 'SPAPI_E_NO_ASSOCIATED_SERVICE - The installation failed because a function driver was not specified for this device instance.',
    0x21A: 'SPAPI_E_NO_DEFAULT_DEVICE_INTERFACE - There is presently no default device interface designated for this interface class.',
    0x21B: 'SPAPI_E_DEVICE_INTERFACE_ACTIVE - The operation cannot be performed because the device interface is currently active.',
    0x21C: 'SPAPI_E_DEVICE_INTERFACE_REMOVED - The operation cannot be performed because the device interface has been removed from the system.',
    0x21D: 'SPAPI_E_BAD_INTERFACE_INSTALLSECT - An interface installation section in this INF is invalid.',
    0x21E: 'SPAPI_E_NO_SUCH_INTERFACE_CLASS - This interface class does not exist in the system.',
    0x21F: 'SPAPI_E_INVALID_REFERENCE_STRING - The reference string supplied for this interface device is invalid.',
    0x220: 'SPAPI_E_INVALID_MACHINENAME - The specified machine name does not conform to UNC naming conventions.',
    0x221: 'SPAPI_E_REMOTE_COMM_FAILURE - A general remote communication error occurred.',
    0x222: 'SPAPI_E_MACHINE_UNAVAILABLE - The machine selected for remote communication is not available at this time.',
    0x223: 'SPAPI_E_NO_CONFIGMGR_SERVICES - The Plug and Play service is not available on the remote machine.',
    0x224: 'SPAPI_E_INVALID_PROPPAGE_PROVIDER - The property page provider registry entry is invalid.',
    0x225: 'SPAPI_E_NO_SUCH_DEVICE_INTERFACE - The requested device interface is not present in the system.',
    0x226: 'SPAPI_E_DI_POSTPROCESSING_REQUIRED - The device\'s co-installer has additional work to perform after installation is complete.',
    0x227: 'SPAPI_E_INVALID_COINSTALLER - The device\'s co-installer is invalid.',
    0x228: 'SPAPI_E_NO_COMPAT_DRIVERS - There are no compatible drivers for this device.',
    0x229: 'SPAPI_E_NO_DEVICE_ICON - There is no icon that represents this device or device type.',
    0x22A: 'SPAPI_E_INVALID_INF_LOGCONFIG - A logical configuration specified in this INF is invalid.',
    0x22B: 'SPAPI_E_DI_DONT_INSTALL - The class installer has denied the request to install or upgrade this device.',
    0x22C: 'SPAPI_E_INVALID_FILTER_DRIVER - One of the filter drivers installed for this device is invalid.',
    0x22D: 'SPAPI_E_NON_WINDOWS_NT_DRIVER - The driver selected for this device does not support Windows.',
    0x22E: 'SPAPI_E_NON_WINDOWS_DRIVER - The driver selected for this device does not support Windows.',
    0x22F: 'SPAPI_E_NO_CATALOG_FOR_OEM_INF - The third-party INF does not contain digital signature information.',
    0x230: 'SPAPI_E_DEVINSTALL_QUEUE_NONNATIVE - An invalid attempt was made to use a device installation file queue for verification of digital signatures relative to other platforms.',
    0x231: 'SPAPI_E_NOT_DISABLEABLE - The device cannot be disabled.',
    0x232: 'SPAPI_E_CANT_REMOVE_DEVINST - The device could not be dynamically removed.',
    0x233: 'SPAPI_E_INVALID_TARGET - Cannot copy to specified target.',
    0x234: 'SPAPI_E_DRIVER_NONNATIVE - Driver is not intended for this platform.',
    0x235: 'SPAPI_E_IN_WOW64 - Operation not allowed in WOW64.',
    0x236: 'SPIAPI_E_SET_SYSTEM_RESTORE_POINT - The operation involving unsigned file copying was rolled back, so that a system restore point could be set.',
    0x237: 'SPAPI_E_INCORRECTLY_COPIED_INF - An INF was copied into the Windows INF directory in an improper manner.',
    0x238: 'SPAPI_E_SCE_DISABLED - The Security Configuration Editor (SCE) APIs have been disabled on this embedded product.',
    0x239: 'SPAPI_E_UNKNOWN_EXCEPTION - An unknown exception was encountered.',
    0x23A: 'SPAPI_E_PNP_REGISTRY_ERROR - A problem was encountered when accessing the Plug and Play registry database.',
    0x23B: 'SPAPI_E_REMOTE_REQUEST_UNSUPPORTED - The requested operation is not supported for a remote machine.',
    0x23C: 'SPAPI_E_NOT_AN_INSTALLED_OEM_INF - The specified file is not an installed OEM INF.',
    0x23D: 'SPAPI_E_INF_IN_USE_BY_DEVICES - One or more devices are presently installed using the specified INF.',
    0x23E: 'SPAPI_E_DI_FUNCTION_OBSOLETE - The requested device install operation is obsolete.',
    0x23F: 'SPAPI_E_NO_AUTHENTICODE_CATALOG - A file could not be verified because it does not have an associated catalog signed via Authenticode(tm).',
    0x240: 'SPAPI_E_AUTHENTICODE_DISALLOWED - Authenticode(tm) signature verification is not supported for the specified INF.',
    0x241: 'SPAPI_E_AUTHENTICODE_TRUSTED_PUBLISHER - The INF was signed with an Authenticode(tm) catalog from a trusted publisher.',
    0x242: 'SPAPI_E_AUTHENTICODE_TRUST_NOT_ESTABLISHED - The publisher of an Authenticode(tm) signed catalog has not yet been established as trusted.',
    0x243: 'SPAPI_E_AUTHENTICODE_PUBLISHER_NOT_TRUSTED - The publisher of an Authenticode(tm) signed catalog was not established as trusted.',
    0x244: 'SPAPI_E_SIGNATURE_OSATTRIBUTE_MISMATCH - The software was tested for compliance with Windows logo requirements on a different version of Windows, and may not be compatible with this version.',
    0x245: 'SPAPI_E_ONLY_VALIDATE_VIA_AUTHENTICODE - The file may only be validated by a catalog signed via Authenticode(tm).',
    0x246: 'SPAPI_E_DEVICE_INSTALLER_NOT_READY - One of the installers for this device cannot perform the installation at this time.',
    0x247: 'SPAPI_E_DRIVER_STORE_ADD_FAILED - A problem was encountered while attempting to add the driver to the store.',
    0x248: 'SPAPI_E_DEVICE_INSTALL_BLOCKED - The installation of this device is forbidden by system policy. Contact your system administrator.',
    0x249: 'SPAPI_E_DRIVER_INSTALL_BLOCKED - The installation of this driver is forbidden by system policy. Contact your system administrator.',
    0x24A: 'SPAPI_E_WRONG_INF_TYPE - The specified INF is the wrong type for this operation.',
    0x24B: 'SPAPI_E_FILE_HASH_NOT_IN_CATALOG - The hash for the file is not present in the specified catalog file. The file is likely corrupt or the victim of tampering.',
    0x24C: 'SPAPI_E_DRIVER_STORE_DELETE_FAILED - A problem was encountered while attempting to delete the driver from the store.',

    0x300: 'SPAPI_E_UNRECOVERABLE_STACK_OVERFLOW - An unrecoverable stack overflow was encountered.',

    0x800: 'CBS_E_INTERNAL_ERROR',
    0x801: 'CBS_E_NOT_INITIALIZED',
    0x802: 'CBS_E_ALREADY_INITIALIZED',
    0x803: 'CBS_E_INVALID_PARAMETER',
    0x804: 'CBS_E_OPEN_FAILED',
    0x805: 'CBS_E_INVALID_PACKAGE',
    0x806: 'CBS_E_PENDING',
    0x807: 'CBS_E_NOT_INSTALLABLE',
    0x808: 'CBS_E_IMAGE_NOT_ACCESSIBLE',
    0x809: 'CBS_E_ARRAY_ELEMENT_MISSING',
    0x80A: 'CBS_E_REESTABLISH_SESSION',
    0x80B: 'CBS_E_PROPERTY_NOT_AVAILABLE',
    0x80C: 'CBS_E_UNKNOWN_UPDATE',
    0x80D: 'CBS_E_MANIFEST_INVALID_ITEM',

    0x80F: 'CBS_E_MANIFEST_VALIDATION_DUPLICATE_ELEMENT',
    0x810: 'CBS_E_MANIFEST_VALIDATION_MISSING_REQUIRED_ATTRIBUTES',
    0x811: 'CBS_E_MANIFEST_VALIDATION_MISSING_REQUIRED_ELEMENTS',
    0x812: 'CBS_E_MANIFEST_VALIDATION_UPDATES_PARENT_MISSING',
    0x813: 'CBS_E_INVALID_INSTALL_STATE',
    0x814: 'CBS_E_INVALID_CONFIG_VALUE',
    0x815: 'CBS_E_INVALID_CARDINALITY',
    0x816: 'CBS_E_DPX_JOB_STATE_SAVED',
    0x817: 'CBS_E_PACKAGE_DELETED',
    0x818: 'CBS_E_IDENTITY_MISMATCH',
    0x819: 'CBS_E_DUPLICATE_UPDATENAME',
    0x81A: 'CBS_E_INVALID_DRIVER_OPERATION_KEY',
    0x81B: 'CBS_E_UNEXPECTED_PROCESSOR_ARCHITECTURE',
    0x81C: 'CBS_E_EXCESSIVE_EVALUATION',
    0x81D: 'CBS_E_CYCLE_EVALUATION',
    0x81E: 'CBS_E_NOT_APPLICABLE ',
    0x81F: 'CBS_E_SOURCE_MISSING',
    0x820: 'CBS_E_CANCEL',
    0x821: 'CBS_E_ABORT',
    0x822: 'CBS_E_ILLEGAL_COMPONENT_UPDATE',
    0x823: 'CBS_E_NEW_SERVICING_STACK_REQUIRED',
    0x824: 'CBS_E_SOURCE_NOT_IN_LIST',
    0x825: 'CBS_E_CANNOT_UNINSTALL',
    0x826: 'CBS_E_PENDING_VICTIM',
    0x827: 'CBS_E_STACK_SHUTDOWN_REQUIRED',
    0x828: 'CBS_E_INSUFFICIENT_DISK_SPACE',
    0x829: 'CBS_E_AC_POWER_REQUIRED',
    0x82A: 'CBS_E_STACK_UPDATE_FAILED_REBOOT_REQUIRED',
    0x82B: 'CBS_E_SQM_REPORT_IGNORED_AI_FAILURES_ON_TRANSACTION_RESOLVE',
    0x82C: 'CBS_E_DEPENDENT_FAILURE',
    0x82D: 'CBS_E_PAC_INITIAL_FAILURE',
    0x82E: 'CBS_E_NOT_ALLOWED_OFFLINE',
    0x82F: 'CBS_E_EXCLUSIVE_WOULD_MERGE',
    0x830: 'CBS_E_IMAGE_UNSERVICEABLE',
    0x831: 'CBS_E_STORE_CORRUPTION - Corruption in the CBS store.',
    0x832: 'CBS_E_STORE_TOO_MUCH_CORRUPTION',
    0x833: 'CBS_S_STACK_RESTART_REQUIRED',

    0x840: 'CBS_E_SESSION_CORRUPT',
    0x841: 'CBS_E_SESSION_INTERRUPTED',
    0x842: 'CBS_E_SESSION_FINALIZED',
    0x843: 'CBS_E_SESSION_READONLY',

    0x84F: 'CBS_E_RESOLVE_FAILED',

    0x88F: 'CBS_E_MANIFEST_VALIDATION_DUPLICATE_ELEMENT',

    0x900: 'CBS_E_XML_PARSER_FAILURE',
    0x901: 'CBS_E_MANIFEST_VALIDATION_MULTIPLE_UPDATE_COMPONENT_ON_SAME_FAMILY_NOT_ALLOWED',
    0x902: 'CBS_E_BUSY',
    0x903: 'CBS_E_INVALID_RECALL',
    0x904: 'CBS_E_MORE_THAN_ONE_ACTIVE_EDITION',
    0x905: 'CBS_E_NO_ACTIVE_EDITION',
    0x906: 'CBS_E_DOWNLOAD_FAILURE',
    0x907: 'CBS_E_GROUPPOLICY_DISALLOWED',
    0x908: 'CBS_E_METERED_NETWORK',
    0x909: 'CBS_E_PUBLIC_OBJECT_LEAK',
    0x90A: 'CBS_E_REPAIR_PACKAGE_CORRUPT',
    0x90B: 'CBS_E_COMPONENT_NOT_INSTALLED_BY_CBS',
    0x90C: 'CBS_E_MISSING_PACKAGE_MAPPING_INDEX',
    0x90D: 'CBS_E_MISSING_PACKAGE_MAPPING_INDEX',
    0x90E: 'CBS_E_EMPTY_PACKAGE_MAPPING_INDEX',
    0x90F: 'CBS_E_WINDOWS_UPDATE_SEARCH_FAILURE',
    0x910: 'CBS_E_WINDOWS_AUTOMATIC_UPDATE_SETTING_DISALLOWED',

    0x920: 'CBS_E_HANG_DETECTED',
    0x921: 'CBS_E_PRIMITIVES_FAILED',
    0x922: 'CBS_E_INSTALLERS_FAILED',
    0x923: 'CBS_E_SAFEMODE_ENTERED',
    0x924: 'CBS_E_SESSIONS_LEAKED',
    0x925: 'CBS_E_INVALID_EXECUTESTATE',

    0x940: 'CBS_E_WUSUS_MAPPING_UNAVAILABLE',
    0x941: 'CBS_E_WU_MAPPING_UNAVAILABLE',
    0x942: 'CBS_E_WUSUS_BYPASS_MAPPING_UNAVAILABLE',
    0x943: 'CBS_E_WUSUS_MISSING_PACKAGE_MAPPING_INDEX',
    0x944: 'CBS_E_WU_MISSING_PACKAGE_MAPPING_INDEX',
    0x945: 'CBS_E_WUSUS_BYPASS_MISSING_PACKAGE_MAPPING_INDEX',
    0x946: 'CBS_E_SOURCE_MISSING_FROM_WUSUS_CAB',
    0x947: 'CBS_E_SOURCE_MISSING_FROM_WUSUS_EXPRESS',
    0x948: 'CBS_E_SOURCE_MISSING_FROM_WU_CAB',
    0x949: 'CBS_E_SOURCE_MISSING_FROM_WU_EXPRESS',
    0x94A: 'CBS_E_SOURCE_MISSING_FROM_WUSUS_BYPASS_CAB',
    0x94B: 'CBS_E_SOURCE_MISSING_FROM_WUSUS_BYPASS_EXPRESS',
    0x94C: 'CBS_E_3RD_PARTY_MAPPING_UNAVAILABLE',
    0x94D: 'CBS_E_3RD_PARTY_MISSING_PACKAGE_MAPPING_INDEX',
    0x94E: 'CBS_E_SOURCE_MISSING_FROM_3RD_PARTY_CAB',
    0x94F: 'CBS_E_SOURCE_MISSING_FROM_3RD_PARTY_EXPRESS',
    0x950: 'CBS_E_INVALID_WINDOWS_UPDATE_COUNT',
    0x951: 'CBS_E_INVALID_NO_PRODUCT_REGISTERED',
    0x952: 'CBS_E_INVALID_ACTION_LIST_PACKAGE_COUNT',
    0x953: 'CBS_E_INVALID_ACTION_LIST_INSTALL_REASON',
    0x954: 'CBS_E_INVALID_WINDOWS_UPDATE_COUNT_WSUS',
    0x955: 'CBS_E_INVALID_PACKAGE_REQUEST_ON_MULTILINGUAL_FOD',

    0x980: 'PSFX_E_DELTA_NOT_SUPPORTED_FOR_COMPONENT',
    0x981: 'PSFX_E_REVERSE_AND_FORWARD_DELTAS_MISSING',
    0x982: 'PSFX_E_MATCHING_COMPONENT_NOT_FOUND',
    0x983: 'PSFX_E_MATCHING_COMPONENT_DIRECTORY_MISSING',
    0x984: 'PSFX_E_MATCHING_BINARY_MISSING',
    0x985: 'PSFX_E_APPLY_REVERSE_DELTA_FAILED',
    0x986: 'PSFX_E_APPLY_FORWARD_DELTA_FAILED',
    0x987: 'PSFX_E_NULL_DELTA_HYDRATION_FAILED',
    0x988: 'PSFX_E_INVALID_DELTA_COMBINATION',
    0x989: 'PSFX_E_REVERSE_DELTA_MISSING',


    0x1000: 'SPAPI_E_ERROR_NOT_INSTALLED - No installed components were detected.',
};

export default setupApiErr;